version: '3.8'

services:
  medinote-back-kc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medinote-back-kc
    ports:
      - "8083:8083"
    environment:
      - LANG=ko_KR.UTF-8
      - LC_ALL=ko_KR.UTF-8
      # === DATABASE ===
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      # === REDIS ===
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      # === JWT ===
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
      # === MAIL ===
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      # === GOOGLE OAUTH ===
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - GOOGLE_SCOPE=${GOOGLE_SCOPE}
      - GOOGLE_AUTH_URI=${GOOGLE_AUTH_URI}
      - GOOGLE_TOKEN_URI=${GOOGLE_TOKEN_URI}
      - GOOGLE_USER_INFO_URI=${GOOGLE_USER_INFO_URI}
      - GOOGLE_USER_NAME_ATTRIBUTE=${GOOGLE_USER_NAME_ATTRIBUTE}
    restart: always
