
server:
  port: 8082
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    import:
      - optional:classpath:secret/db.yml
  application:
    name: medinote
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  task:
    scheduling:
      pool:
        size: 2
      thread-name-prefix: news-scheduler-
news:
  scheduler:
    enabled: true