name: Deploy MediNote KC to Oracle Server

on:
  push:
    branches:
      - master            # master 브랜치에 push될 때만 실행
    paths:
      - 'medinote_back_kc/**'  # medinote_back_kc 폴더 변경만 감지

jobs:
  deploy:
    name: Build & Deploy on Oracle Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Spring Boot Project
        working-directory: ./medinote_back_kc
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Transfer and Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/MediNote_Back/medinote_back_kc
            sudo docker-compose down
            sudo git pull origin master
            sudo docker-compose up --build -d
